In [2]:
import pandas as pd

s1 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])
s2 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

s3 = pd.Series([10, 20, 30, 40], name="S3")
s4 = pd.Series([10, 20, 30, 40], name="S4")

In [3]:
test = [["이름", "나이", "국어"],
        ["철수", 25, 87],
        ["영희", 23, 79]]

df = pd.DataFrame(test)

In [4]:
df

    0   1   2
0  이름  나이  국어
1  철수  25  87
2  영희  23  79

In [9]:
data1 = pd.read_csv('C:/Users/human/ku-python/data/treatment.csv')

In [10]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1000 non-null   object
 1   treatmenta  908 non-null    float64
 2   treatmentb  906 non-null    float64
dtypes: float64(2), object(1)
memory usage: 23.6+ KB

In [11]:
data1.describe()

       treatmenta  treatmentb
count  908.000000  906.000000
mean    48.408590   51.163355
std     29.315442   28.840423
min      0.000000    0.000000
25%     23.000000   26.000000
50%     49.000000   51.000000
75%     74.000000   76.000000
max    100.000000  100.000000

In [ ]:
# head나 tail은 dafault가 5이다.
data1.head()

     name  treatmenta  treatmentb
0      서연        65.0        83.0
1  Olivia         2.0        91.0
2      도윤        40.0        14.0
3      예진        13.0         NaN
4    Emma        25.0         1.0

In [13]:
data1.tail(10)

        name  treatmenta  treatmentb
990   Robert        51.0        31.0
991  Michael        11.0        99.0
992       영희        38.0        74.0
993     John        49.0        35.0
994     John         5.0         NaN
995    Alice        59.0        44.0
996       예진        99.0         5.0
997       현우        57.0        86.0
998       준호        76.0        41.0
999   Sophia        13.0        44.0

In [20]:
# sample은 무작위 테이터를 출력한다.
data1.sample(10)

       name  treatmenta  treatmentb
598    Emma        17.0        14.0
648      철수        48.0         NaN
482  Robert        49.0        56.0
474      서연        86.0        54.0
892    John        14.0        29.0
307    John         NaN        94.0
877    John        29.0        41.0
111      지연        11.0        74.0
139   James        88.0        39.0
440      예진        53.0        90.0

In [22]:
data2 = pd.read_excel("C:/Users/human/ku-python/data/treatment.xlsx")

In [23]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1000 non-null   object
 1   treatmenta  908 non-null    float64
 2   treatmentb  906 non-null    float64
dtypes: float64(2), object(1)
memory usage: 23.6+ KB

In [24]:
pd.DataFrame(data=[["abc", "1234", "name1"], ["def", "1234", "name2"]], columns=["id", "pass", "name"])

    id  pass   name
0  abc  1234  name1
1  def  1234  name2

In [ ]:
data1['treatmenta']     # Dictionary 방식으로 데이터 가져오기

0      65.0
1       2.0
2      40.0
3      13.0
4      25.0
       ...
995    59.0
996    99.0
997    57.0
998    76.0
999    13.0
Name: treatmenta, Length: 1000, dtype: float64

In [29]:
# Fency index 방식 / 다양한 조건들에 해당하는 열 or 값들의 데이터들을 뽑아내기 위해 사용
data1[["treatmenta", "treatmentb"]]

     treatmenta  treatmentb
0          65.0        83.0
1           2.0        91.0
2          40.0        14.0
3          13.0         NaN
4          25.0         1.0
..          ...         ...
995        59.0        44.0
996        99.0         5.0
997        57.0        86.0
998        76.0        41.0
999        13.0        44.0

[1000 rows x 2 columns]

In [ ]:
# 조건 동시연산 / Series를 ()로 감싸고 &(and), |(or) 연산 
data1[(data1["treatmenta"] > 50) & (data1["treatmentb"] < 30)]

         name  treatmenta  treatmentb
16      David        76.0         6.0
17         도윤        77.0        19.0
18   Isabella        86.0         9.0
26         철수        95.0        19.0
27         민수        54.0        15.0
..        ...         ...         ...
967        지연        75.0        14.0
982      Emma        79.0        24.0
985     David        84.0        11.0
989     David        82.0        15.0
996        예진        99.0         5.0

[122 rows x 3 columns]

In [ ]:
# 숫자형 데이터 타입이 있는 열만 가져옴
data1.select_dtypes(include=["number"])

     treatmenta  treatmentb
0          65.0        83.0
1           2.0        91.0
2          40.0        14.0
3          13.0         NaN
4          25.0         1.0
..          ...         ...
995        59.0        44.0
996        99.0         5.0
997        57.0        86.0
998        76.0        41.0
999        13.0        44.0

[1000 rows x 2 columns]

In [ ]:
# loc       index 이름으로 접근
# iloc      index 숫자로 접근

# data1.loc("지연")
data1.iloc[2:10]

# 0번째 2번째 행의 1번째 0번째 열을 가져옴
data1.iloc[[0, 2], [1, 0]]

   treatmenta name
0        65.0   서연
2        40.0   도윤

In [51]:
import numpy as np

# Messy data / 정리되지 않은 데이터
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Chris", "Tom"],
    "Math": [85, 78, np.nan, 67],
    "Science": [90, 85, 88, 78],
    "English": [88, 92, np.nan, np.nan]
})

In [50]:
df

    Name  Math  Science  English
0  Alice  85.0       90     88.0
1    Bob  78.0       85     92.0
2  Chris   NaN       88      NaN
3    Tom  67.0       78      NaN

In [ ]:
# melt = 컬럼을 축약함
# id_vars = 건들이지 않음 || var_name = Column Name을 한 컬럼으로 만듬 || value_name = 실제 데이터들을 한 컬럼으로 만듬

df.melt(id_vars=["Name"], var_name="Subject", value_name="Score")

     Name  Subject  Score
0   Alice     Math   85.0
1     Bob     Math   78.0
2   Chris     Math    NaN
3     Tom     Math   67.0
4   Alice  Science   90.0
5     Bob  Science   85.0
6   Chris  Science   88.0
7     Tom  Science   78.0
8   Alice  English   88.0
9     Bob  English   92.0
10  Chris  English    NaN
11    Tom  English    NaN

In [53]:
df['Science'] = df['Science'].astype('float32')

In [56]:
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Math     3 non-null      float64
 2   Science  4 non-null      float32
 3   English  2 non-null      float64
dtypes: float32(1), float64(2), object(1)
memory usage: 244.0+ bytes

In [61]:
df.rename(columns={"Name":"이름"})

      이름  Math  Science  English
0  Alice  85.0     90.0     88.0
1    Bob  78.0     85.0     92.0
2  Chris   NaN     88.0      NaN
3    Tom  67.0     78.0      NaN