## 강의 개요

강의 제목: 파이썬 프로그래밍 입문

대상: 프로그래밍 경험이 없는 초보자

목표:
* Pandas의 기본 개념 및 데이터프레임 생성 방법 학습
* 데이터 불러오기, 정제, 변환 및 결측값 처리 실습
* 실전 데이터 정제 및 가공 실습

## 데이터 분석

> 데이터 분석은 데이터를 수집 및 정제 하여 유의미한 정보를 도출하는 과정 <br>
> 이를 통해 패턴을 발견하고 문제를 해결하며 의사결정에 활용한다

## 데이터 분석 활용 사례

<img src="사진/데이터 분석 활용사례1.png" alt="데이터 분석 활용 사례1"/>

<img src="사진/데이터 분석 활용사례2.png" alt="데이터 분석 활용 사례2"/>

[출처]
https://zero-base.co.kr/event/media_insight_contents_DS_bigdata_examples
<br>
[참고]
https://blog.naver.com/codeitofficial/223412571130

## 데이터 분석 절차

<img src="사진/데이터 분석 절차.png" alt="데이터 분석 절차"/>

> 일반적으로 자료 수집부터 시각화까지 진행 후 결과 해석 진행

[출처]
https://m.post.naver.com/viewer/postView.naver?volumeNo=38182828&memberNo=10728965&navigationType=push

## 데이터 분석 도구

[언어]
- Python
- R
- SQL

[Python]
1. 데이터 수집 도구 
- Requests
- BeautifulSoup
- Scrapy 
- Playwright 
- Selenium 

2. 데이터 처리 및 분석 도구 
- Numpy 
- Pandas 
- Dask 
- Polars 

3. 데이터 시각화 도구 
- Matplotlib 
- Seaborn 
- Plotly 
- Bokeh 

4. 통계 및 머신러닝 분석 도구 
- SciPy 
- Statsmodels
- Scikit-learn
- XGBoost/LightGBM
- Tensorflow/PyTorch

## Pandas

<img src="사진/pandas.png" alt="pandas"/>

[시간 09:00 ~ 10:00]

In [59]:
import pandas as pd

In [60]:
pd.__version__

'2.2.3'

## 데이터 종류

1. 정형 데이터
- 규칙적인 구조를 갖고 있고, 일반적으로 테이블 형식으로 저장되는 데이터 
- 예) 
- csv 
- excel 
- db table 
2. 비정형 데이터 
- 명확한 구조나 형식이 없는 데이터 
- 예)
- 텍스트 
- 이미지 및 비디오  
- 오디오
3. 반정형 데이터 
- 일정한 구조를 가지고 있지만, 고정된 형식이 아닌 데이터 
- 예) 
- XML
- JSON
- HTML 
- 로그 파일 
- 메일 헤더

## 구조

<img src="사진/series.png" alt="series"/>

### Series

In [61]:
s1 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

In [62]:
s2 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])

In [63]:
s1 + s2

A    20
B    40
C    60
D    80
dtype: int64

In [64]:
s1 * s2

A     100
B     400
C     900
D    1600
dtype: int64

In [65]:
s1 / s2

A    1.0
B    1.0
C    1.0
D    1.0
dtype: float64

In [66]:
s1 - s2

A    0
B    0
C    0
D    0
dtype: int64

In [67]:
s3 = pd.Series([10, 20, 30], name='A')
s4 = pd.Series(["X", "Y", "Z"], name='B')

In [68]:
df = pd.DataFrame({'숫자': s3, '알파벳': s4})

In [69]:
df

   숫자 알파벳
0  10   X
1  20   Y
2  30   Z

In [70]:
pd.concat([s3, s4], axis=1) # axis 1 -> 열 연산

    A  B
0  10  X
1  20  Y
2  30  Z

In [71]:
pd.concat([s3, s4], axis=0) # axis 0 -> 행 연산

0    10
1    20
2    30
0     X
1     Y
2     Z
dtype: object

### DataFrame

<img src="사진/dataframe.png" alt="dataframe"/>

In [72]:
data = {'이름': ['김철수', '이영희', '박지훈'],
        '나이': [23, 25, 22],
        '국어': [90, 85, 80]}

df = pd.DataFrame(data)

In [73]:
df

    이름  나이  국어
0  김철수  23  90
1  이영희  25  85
2  박지훈  22  80

## 데이터 탐색 및 기본 조작

### 데이터 분석 전 확인하는 5가지

1. info : 데이터의 기본 정보를 보여준다
2. describe : 숫자형태인 데이터에 대해서 기본 통계값을 보여준다
3. head : default로 앞에서 5개 데이터만 불러온다 (앞에서부터 보고싶은 데이터 갯수 입력 가능)
4. tail : head와 반대로 뒤에서 부터 데이터를 불러온다
5. sample : 랜덤으로 하나의 데이터를 불러온다

> 데이터를 분석하기 전에 분석할 가치가 있는 데이터인지 확인하기 위한 작업이다 <br>
> 1. 데이터 양이 충분한가? -> 데이터 수집이 더 필요할 수 있기 때문 
> 2. 결측 데이터가 너무 많지는 않은가? -> 데이터 활용 가치가 없을 수 있기 때문 
> 3. 데이터의 크기는 얼만한가? -> 데이터 크기가 너무 크면 오류가 나거나 실행 속도가 느려질 수 있기 때문

큰 수의 법칙
오컴의 면도날

In [74]:
df

    이름  나이  국어
0  김철수  23  90
1  이영희  25  85
2  박지훈  22  80

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      object
 1   나이      3 non-null      int64
 2   국어      3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [76]:
df.describe()

              나이    국어
count   3.000000   3.0
mean   23.333333  85.0
std     1.527525   5.0
min    22.000000  80.0
25%    22.500000  82.5
50%    23.000000  85.0
75%    24.000000  87.5
max    25.000000  90.0

In [77]:
df.describe(include='object')

         이름
count     3
unique    3
top     김철수
freq      1

In [78]:
df.head(2)

    이름  나이  국어
0  김철수  23  90
1  이영희  25  85

In [79]:
df.tail(2)

    이름  나이  국어
1  이영희  25  85
2  박지훈  22  80

In [80]:
df.sample(2)

    이름  나이  국어
2  박지훈  22  80
0  김철수  23  90

## Pandas Dataframe으로 불러오는 3가지 방법

1. pd.read_xxx
2. pd.DataFrame 
3. pd.DataFrame.from_dict

In [81]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names: if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
  Column(s) to use as row label(s), denoted either by column labels or column
  indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
  will be formed for the row labels.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g., when you have a malformed file with delimiters at
  the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion.

    .. versionadded:: 1.5.0

        Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
        the default determines the ``dtype`` of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The 'pyarrow' engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
    per-column ``NA`` values.  By default the following values are interpreted as
    ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
    "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
    "n/a", "nan", "null ".

keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of ``NA`` values placed in non-numeric columns.

    .. deprecated:: 2.2.0
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
      ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
    * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
      as a single date column. Values are joined with a space before parsing.
    * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
      result 'foo'. Values are joined with a space before parsing.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
    format of the ``datetime`` strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If ``True`` and ``parse_dates`` specifies combining multiple columns then
    keep the original columns.
date_parser : Callable, optional
    Function to use for converting a sequence of string columns to an array of
    ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. pandas will try to call ``date_parser`` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by ``parse_dates`` into a single array
    and pass that; and 3) call ``date_parser`` once for each row using one or
    more strings (corresponding to the columns defined by ``parse_dates``) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`~pandas.to_datetime` as-needed.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates when used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
        time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
        and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
    characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
   When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - Callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine='python'``

    .. versionchanged:: 2.2.0

        - Callable, function with signature
          as described in `pyarrow documentation
          <https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_ when ``engine='pyarrow'``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be

- sep: CSV 파일의 구분자 지정. 기본값 "," (Comma-Separated Values) (, ; \t |)
- delimiter: sep랑 동일 (numpy에서 사용되던 파라미터 이름)
- header: CSV 파일의 열 이름을 정의하는 행을 지정. ex) header=0 이면 첫번째 행을 열 이름으로 사용 / header=None이면 첫번째 행을 데이터로 간주
- names: header 파라미터와 같이 사용하고 열 이름을 지정할때 사용
- index_col: 특정 열을 인덱스로 설정할 때 사용
- usecols: 특정 열만 선택하여 불러올 때 사용 
- dtype: 열 데이터 유형을 지정할 때 사용 
- engine: 엔진 지정 (c or python)

In [82]:
data1 = pd.read_csv('c:/Users/human/ku-python/data/treatment.csv')

In [83]:
data1

       name  treatmenta  treatmentb
0        서연        65.0        83.0
1    Olivia         2.0        91.0
2        도윤        40.0        14.0
3        예진        13.0         NaN
4      Emma        25.0         1.0
..      ...         ...         ...
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0
999  Sophia        13.0        44.0

[1000 rows x 3 columns]

In [84]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1000 non-null   object
 1   treatmenta  908 non-null    float64
 2   treatmentb  906 non-null    float64
dtypes: float64(2), object(1)
memory usage: 23.6+ KB

In [85]:
data1.describe()

       treatmenta  treatmentb
count  908.000000  906.000000
mean    48.408590   51.163355
std     29.315442   28.840423
min      0.000000    0.000000
25%     23.000000   26.000000
50%     49.000000   51.000000
75%     74.000000   76.000000
max    100.000000  100.000000

In [86]:
# pip install openpyxl 
data1 = pd.read_excel('data/treatment.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'data/treatment.xlsx'

In [ ]:
data1

       name  treatmenta  treatmentb
0        서연        65.0        83.0
1    Olivia         2.0        91.0
2        도윤        40.0        14.0
3        예진        13.0         NaN
4      Emma        25.0         1.0
..      ...         ...         ...
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0
999  Sophia        13.0        44.0

[1000 rows x 3 columns]

In [ ]:
pd.DataFrame(data=[['abc', '1234', 'name1'], ['def', '1234', 'name2']],
            columns=['아이디', '비밀번호', '이름'])

   아이디  비밀번호     이름
0  abc  1234  name1
1  def  1234  name2

In [ ]:
data2 = pd.DataFrame(data=[['abc', '1234', 'name1'], ['def', '1234', 'name2']], columns=['아이디', '비밀번호', '이름'])

In [ ]:
data2

   아이디  비밀번호     이름
0  abc  1234  name1
1  def  1234  name2

In [ ]:
data3 = {'아이디': ['abc', 'def'],  '비밀번호': ['1234', '1234'], '이름': ['name1', 'name2']}
data3 = pd.DataFrame.from_dict(data3)
data3_ = pd.DataFrame(data3)

In [ ]:
data3

{'아이디': ['abc', 'def'], '비밀번호': ['1234', '1234'], '이름': ['name1', 'name2']}

In [ ]:
data3

   아이디  비밀번호     이름
0  abc  1234  name1
1  def  1234  name2

In [ ]:
data3_

   아이디  비밀번호     이름
0  abc  1234  name1
1  def  1234  name2

### Quiz1 
> quiz1.csv 파일을 불러오시오. <br>
> 단, 컬럼은 3개 (Name, Age, Salary)인 데이터 프레임으로 불러오시오

In [ ]:
pd.read_csv("c:/Users/human/ku-python/data/quiz1.csv", sep=';', usecols=["Name", "Age", "Salary"])

      Name  Age  Salary
0  티모시 샬라메   25   50000
1    스티븐 연   30   60000
2    데미 무어   35   70000
3   스탠리 투치   40   80000

In [ ]:
pd.read_csv("c:/Users/human/ku-python/data/quiz1.csv", sep=';', usecols=[1,2,3])

      Name  Age  Salary
0  티모시 샬라메   25   50000
1    스티븐 연   30   60000
2    데미 무어   35   70000
3   스탠리 투치   40   80000

In [ ]:
# pd.read_csv('c:/Users/human/ku-python/data/quiz1.csv', sep=';', index_col=False, usecols=[1, 2, 3])

      Name  Age  Salary
0  티모시 샬라메   25   50000
1    스티븐 연   30   60000
2    데미 무어   35   70000
3   스탠리 투치   40   80000

### 열 뽑는 4가지 방법

1. dictionary ([''])
2. attribute (.)
3. fancy indexing
    - numpy에서 배열의 특정 요소를 인덱싱할 때 리스트나 배열을 사용하여 여러 개의 인덱스를 한 번에 선택하는 방식
    - 복사된 배열을 반환하여 기존 배열을 수정하지 않음
4. data type (select_dtypes)

In [ ]:
data1.columns

Index(['name', 'treatmenta', 'treatmentb'], dtype='object')

In [ ]:
data1['treatmenta']

0      65.0
1       2.0
2      40.0
3      13.0
4      25.0
       ...
995    59.0
996    99.0
997    57.0
998    76.0
999    13.0
Name: treatmenta, Length: 1000, dtype: float64

In [ ]:
data1.treatmenta

0      65.0
1       2.0
2      40.0
3      13.0
4      25.0
       ...
995    59.0
996    99.0
997    57.0
998    76.0
999    13.0
Name: treatmenta, Length: 1000, dtype: float64

In [ ]:
type(test)

pandas.core.frame.DataFrame

In [91]:
data1[['treatmentb', 'treatmenta']]

     treatmentb  treatmenta
0          83.0        65.0
1          91.0         2.0
2          14.0        40.0
3           NaN        13.0
4           1.0        25.0
..          ...         ...
995        44.0        59.0
996         5.0        99.0
997        86.0        57.0
998        41.0        76.0
999        44.0        13.0

[1000 rows x 2 columns]

In [ ]:
data1['treatmenta'] > 50

0       True
1      False
2      False
3      False
4      False
       ...
995     True
996     True
997     True
998     True
999    False
Name: treatmenta, Length: 1000, dtype: bool

In [ ]:
data1[data1['treatmenta'] > 50]

       name  treatmenta  treatmentb
0        서연        65.0        83.0
6     David        74.0        72.0
10       서연        82.0        51.0
11     John        93.0        72.0
13    David        65.0        84.0
..      ...         ...         ...
990  Robert        51.0        31.0
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0

[427 rows x 3 columns]

In [ ]:
data1[(data1['treatmenta'] > 50) | (data1['treatmentb'] < 30)]

       name  treatmenta  treatmentb
0        서연        65.0        83.0
2        도윤        40.0        14.0
4      Emma        25.0         1.0
6     David        74.0        72.0
9        예진        11.0         5.0
..      ...         ...         ...
990  Robert        51.0        31.0
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0

[558 rows x 3 columns]

In [ ]:
data1.select_dtypes(include=['number']) # number 또는 object 열 선택

     treatmenta  treatmentb
0          65.0        83.0
1           2.0        91.0
2          40.0        14.0
3          13.0         NaN
4          25.0         1.0
..          ...         ...
995        59.0        44.0
996        99.0         5.0
997        57.0        86.0
998        76.0        41.0
999        13.0        44.0

[1000 rows x 2 columns]

In [ ]:
data1.select_dtypes(include=['object'])

       name
0        서연
1    Olivia
2        도윤
3        예진
4      Emma
..      ...
995   Alice
996      예진
997      현우
998      준호
999  Sophia

[1000 rows x 1 columns]

### Quiz2
> pathogenicity_scores.csv 파일을 불러오고, SCORE_A 가 0.5 이상인 Patient_ID, Mutation_ID, SCORE_A 컬럼을 불러오시오

In [ ]:
data = pd.read_csv('c:/Users/human/ku-python/data/pathogenicity_scores.csv', usecols=['Patient_ID', 'Mutation_ID', 'SCORE_A'])
data = data[data['SCORE_A'] > 0.5]

In [ ]:
data = pd.read_csv('c:/Users/human/ku-python/data/pathogenicity_scores.csv')
data = data[['Patient_ID', 'Mutation_ID', 'SCORE_A']]
data[data['SCORE_A'] > 0.5]

       Patient_ID  Mutation_ID  SCORE_A
1               1            2    0.504
7               1            8    0.934
30              1           31    0.665
31              1           32    0.591
32              1           33    0.591
...           ...          ...      ...
29420         114        22829    0.521
29424         114        22833    0.579
29463         114         9733    0.573
29471         114        22860    0.735
29472         114        22861    0.735

[4111 rows x 3 columns]

In [ ]:
# data = pd.read_csv('c:/Users/human/ku-python/data/pathogenicity_scores.csv')
# data[['Patient_ID', 'Mutation_ID', 'SCORE_A']][data['SCORE_A'] > 0.5]

       Patient_ID  Mutation_ID  SCORE_A
1               1            2    0.504
7               1            8    0.934
30              1           31    0.665
31              1           32    0.591
32              1           33    0.591
...           ...          ...      ...
29420         114        22829    0.521
29424         114        22833    0.579
29463         114         9733    0.573
29471         114        22860    0.735
29472         114        22861    0.735

[4111 rows x 3 columns]

### 행 뽑는 2가지 장법

1. loc  # index 명으로 접근
2. iloc # index 숫자로 접근

In [ ]:
data1 = pd.read_csv('c:/Users/human/ku-python/data/treatment.csv', index_col='name')

In [ ]:
data1.index

Index(['서연', 'Olivia', '도윤', '예진', 'Emma', 'Emma', 'David', '지연', 'Michael',
       '예진',
       ...
       'Robert', 'Michael', '영희', 'John', 'John', 'Alice', '예진', '현우', '준호',
       'Sophia'],
      dtype='object', name='name', length=1000)

In [ ]:
data1.loc['도윤']

      treatmenta  treatmentb
name
도윤          40.0        14.0
도윤          77.0        19.0
도윤           4.0        97.0
도윤          56.0        92.0
도윤           NaN        85.0
도윤          35.0        17.0
도윤          27.0        41.0
도윤          64.0         4.0
도윤          85.0        87.0
도윤          65.0        72.0
도윤          67.0        54.0
도윤          77.0        27.0
도윤           NaN         NaN
도윤          90.0        39.0
도윤           0.0        94.0
도윤          25.0         NaN
도윤          36.0        22.0
도윤          49.0        58.0
도윤           9.0        11.0
도윤           5.0        30.0
도윤          11.0        27.0
도윤           0.0        88.0
도윤          72.0        29.0
도윤          62.0        78.0
도윤          19.0        74.0
도윤          14.0        59.0
도윤          86.0        19.0
도윤          81.0        78.0
도윤          52.0        60.0
도윤          25.0        69.0
도윤          71.0        45.0
도윤          93.0        53.0
도윤          54.0        42.0
도윤          94.0        73.0
도윤          31.0        48.0
도윤          78.0        65.0
도윤          86.0        81.0
도윤          57.0        74.0
도윤          12.0        73.0
도윤           1.0         NaN
도윤          33.0        40.0
도윤          18.0        49.0
도윤          35.0        46.0
도윤          67.0        41.0
도윤          15.0        94.0
도윤          31.0        88.0
도윤          52.0        22.0
도윤          54.0        99.0
도윤          12.0        49.0
도윤           NaN         NaN
도윤          43.0        64.0
도윤           NaN        83.0
도윤          38.0        73.0
도윤          53.0        19.0
도윤          45.0        68.0
도윤          58.0        58.0
도윤          85.0        68.0
도윤          90.0        25.0
도윤           2.0        78.0

In [ ]:
data1.loc['도윤'][-9:-2] # 인덱스의 값이 중복이 있을때는 slicing이 안됨

      treatmenta  treatmentb
name
도윤          43.0        64.0
도윤           NaN        83.0
도윤          38.0        73.0
도윤          53.0        19.0
도윤          45.0        68.0
도윤          58.0        58.0
도윤          85.0        68.0

In [ ]:
data1

        treatmenta  treatmentb
name
서연            65.0        83.0
Olivia         2.0        91.0
도윤            40.0        14.0
예진            13.0         NaN
Emma          25.0         1.0
...            ...         ...
Alice         59.0        44.0
예진            99.0         5.0
현우            57.0        86.0
준호            76.0        41.0
Sophia        13.0        44.0

[1000 rows x 2 columns]

In [ ]:
data1.iloc[2:10]

         treatmenta  treatmentb
name
도윤             40.0        14.0
예진             13.0         NaN
Emma           25.0         1.0
Emma            NaN        89.0
David          74.0        72.0
지연              2.0        33.0
Michael         NaN         NaN
예진             11.0         5.0

In [ ]:
data1.head(4)

        treatmenta  treatmentb
name
서연            65.0        83.0
Olivia         2.0        91.0
도윤            40.0        14.0
예진            13.0         NaN

In [ ]:
data1.iloc[[0,2], [1,0]]

      treatmentb  treatmenta
name
서연          83.0        65.0
도윤          14.0        40.0

### Quiz3
> pathogenicity_scores 파일에서 <br>
> 1000번째 행에서 1100번째 행까지 출력하고, <br>
> SCORE_B가 0.5 이상인 행을 필터링 하시오.

In [ ]:
data = pd.read_csv('c:/Users/human/ku-python/data/pathogenicity_scores.csv')

In [ ]:
data.iloc[999:1099][data.iloc[999:1099]['SCORE_B'] > 0.5]

      Patient_ID  Mutation_ID  LABEL  SCORE_A   SCORE_B   SCORE_C
999            5         1168      0    0.382  0.893459  0.450833
1001           5         1170      0    0.259  0.699785  0.731167
1006           5          157      0    0.174  0.573609  0.419222
1016           5         1181      0    0.340  0.891866  0.750785
1018           5         1183      0    0.037  0.811767  0.338075
1023           5         1188      0    0.293  0.523025  0.490200
1026           5          178      0    0.090  0.652320  0.240912
1027           5          179      0    0.146  0.770625  0.238595
1033           5          440      0    0.053  0.661808  0.231759
1038           5         1193      0    0.879  0.918489  0.527856
1045           5         1200      0    0.494  0.830115  0.686067
1046           5         1201      0    0.376  0.625292  0.428569
1054           5         1209      0    0.303  0.605360  0.397886
1063           5         1218      0    0.054  0.572905  0.489607
1066           5         1220      0    0.371  0.787886  0.551190
1068           5         1222      0    0.299  0.687113  0.621561
1069           5         1223      0    0.299  0.685279  0.621561
1073           5          237      0    0.201  0.751908  0.322244
1074           5          238      0    0.058  0.525156  0.303945
1076           5         1226      0    0.016  0.645394  0.244860
1080           5         1230      0    0.422  0.704952  0.751141
1084           5         1234      0    0.672  0.861287  0.907498
1086           5         1236      0    0.100  0.689549  0.358116
1091           5         1241      0    0.350  0.741949  0.801350
1093           5          758      0    0.231  0.959059  0.815405
1094           5          759      0    0.231  0.958880  0.815405
1095           5         1243      0    0.345  0.933562  0.483675
1096           5         1244      0    0.345  0.932730  0.483675

In [ ]:
# data = pd.read_csv('c:/Users/human/ku-python/data/pathogenicity_scores.csv')
# data.iloc[999:1099][data.iloc[999:1099]['SCORE_B'] > 0.5]

## 데이터 정제 및 결측값 처리

### Tidy data
> 깔끔하게 정제된 데이터. 이상적인 형식의 데이터 구조. <br>
> 수집한 데이터가 충분히 정제 되어 Tidy data로 만들어져야, 분석과 시각화가 용이해진다

[Tidy data의 조건]
1. 각 변 수는 하나의 열에 있어야 한다 
2. 각 관측값은 하나의 행에 있어야 한다 
3. 각 관측 단위는 하나의 테이블로 구성되어야 한다

[출처]
https://vita.had.co.nz/papers/tidy-data.pdf

In [95]:
import numpy as np

# Messy Data (정리되지 않은 데이터)
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Chris", "Tom"],
    "Math": [85, 78, np.nan, 67],
    "Science": [90, 85, 88, 78],
    "English": [88, 92, np.nan, np.nan]
})

In [ ]:
df

    Name  Math  Science  English
0  Alice  85.0       90     88.0
1    Bob  78.0       85     92.0
2  Chris   NaN       88      NaN
3    Tom  67.0       78      NaN

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Math     3 non-null      float64
 2   Science  4 non-null      int64
 3   English  2 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 260.0+ bytes

In [92]:
df.melt?

Signature:
df.melt(
    id_vars=None,
    value_vars=None,
    var_name=None,
    value_name: 'Hashable' = 'value',
    col_level: 'Level | None' = None,
    ignore_index: 'bool' = True,
) -> 'DataFrame'
Docstring:
Unpivot a DataFrame from wide to long format, optionally leaving identifiers set.

This function is useful to massage a DataFrame into a format where one
or more columns are identifier variables (`id_vars`), while all other
columns, considered measured variables (`value_vars`), are "unpivoted" to
the row axis, leaving just two non-identifier columns, 'variable' and
'value'.

Parameters
----------
id_vars : scalar, tuple, list, or ndarray, optional
    Column(s) to use as identifier variables.
value_vars : scalar, tuple, list, or ndarray, optional
    Column(s) to unpivot. If not specified, uses all columns that
    are not set as `id_vars`.
var_name : scalar, default None
    Name to use for the 'variable' column. If None it uses
    ``frame.columns.name`` or 'variable'.
value_name : scalar, default 'value'
    Name to use for the 'value' column, can't be an existing column label.
col_level : scalar, optional
    If columns are a MultiIndex then use this level to melt.
ignore_index : bool, default True
    If True, original index is ignored. If False, the original index is retained.
    Index labels will be repeated as necessary.

Returns
-------
DataFrame
    Unpivoted DataFrame.

See Also
--------
melt : Identical method.
pivot_table : Create a spreadsheet-style pivot table as a DataFrame.
DataFrame.pivot : Return reshaped DataFrame organized
    by given index / column values.
DataFrame.explode : Explode a DataFrame from list-like
        columns to long format.

Notes
-----
Reference :ref:`the user guide <reshaping.melt>` for more examples.

Examples
--------
>>> df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
...                    'B': {0: 1, 1: 3, 2: 5},
...                    'C': {0: 2, 1: 4, 2: 6}})
>>> df
   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

>>> df.melt(id_vars=['A'], value_vars=['B'])
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

>>> df.melt(id_vars=['A'], value_vars=['B', 'C'])
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

The names of 'variable' and 'value' columns can be customized:

>>> df.melt(id_vars=['A'], value_vars=['B'],
...         var_name='myVarname', value_name='myValname')
   A myVarname  myValname
0  a         B          1
1  b         B          3
2  c         B          5

Original index values can be kept around:

>>> df.melt(id_vars=['A'], value_vars=['B', 'C'], ignore_index=False)
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
0  a        C      2
1  b        C      4
2  c        C      6

If you have multi-index columns:

>>> df.columns = [list('ABC'), list('DEF')]
>>> df
   A  B  C
   D  E  F
0  a  1  2
1  b  3  4
2  c  5  6

>>> df.melt(col_level=0, id_vars=['A'], value_vars=['B'])
   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

>>> df.melt(id_vars=[('A', 'D')], value_vars=[('B', 'E')])
  (A, D) variable_0 variable_1  value
0      a          B          E      1
1      b          B          E      3
2      c          B          E      5
File:      c:\users\human\anaconda3\envs\test\lib\site-packages\pandas\core\frame.py
Type:      method

In [ ]:
df.melt(id_vars=["Name"], var_name="Subject", value_name="Score")

    Name  Math  Subject  Score
0  Alice  85.0  Science   90.0
1    Bob  78.0  Science   85.0
2  Chris   NaN  Science   88.0
3    Tom  67.0  Science   78.0
4  Alice  85.0  English   88.0
5    Bob  78.0  English   92.0
6  Chris   NaN  English    NaN
7    Tom  67.0  English    NaN

In [ ]:
tidy_df = df.melt(id_vars=["Name"], var_name="Subject", value_name="Score")

In [ ]:
tidy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     12 non-null     object
 1   Subject  12 non-null     object
 2   Score    9 non-null      float64
dtypes: float64(1), object(2)
memory usage: 420.0+ bytes

### 데이터 타입 변경하기
- astype
- to_numeric
- to_datetime

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Math     3 non-null      float64
 2   Science  4 non-null      int64
 3   English  2 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 260.0+ bytes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Math     3 non-null      float64
 2   Science  4 non-null      int64
 3   English  2 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 260.0+ bytes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Math     3 non-null      float64
 2   Science  4 non-null      int64
 3   English  2 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 260.0+ bytes

In [ ]:
df['Science'] = pd.to_numeric(df['Science'], errors='coerce')

In [ ]:
tidy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     12 non-null     object
 1   Subject  12 non-null     object
 2   Score    9 non-null      float64
dtypes: float64(1), object(2)
memory usage: 420.0+ bytes

In [ ]:
tidy_df['Subject'] = tidy_df['Subject'].astype('category')

In [ ]:
tidy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     12 non-null     object
 1   Subject  12 non-null     category
 2   Score    9 non-null      float64
dtypes: category(1), float64(1), object(1)
memory usage: 468.0+ bytes

In [ ]:
df = pd.DataFrame({'date_col': ['2024-03-01', '2025-06-15', 'invalid_date']})

In [ ]:
df

       date_col
0    2024-03-01
1    2025-06-15
2  invalid_date

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date_col  3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [ ]:
df['date_col'] = pd.to_datetime(df['date_col'], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date_col  2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 156.0 bytes

In [ ]:
df

    date_col
0 2024-03-01
1 2025-06-15
2        NaT

### 컬럼 및 행 수정하기

In [ ]:
# 컬럼 명 수정하기
tidy_df.rename(columns={'Name': '이름', 'Subject': '과목', 'Score': '점수'}, inplace=True)

In [ ]:
tidy_df.head(3)

      이름    과목    점수
0  Alice  Math  85.0
1    Bob  Math  78.0
2  Chris  Math   NaN

In [ ]:
tidy_df['과목'] = tidy_df['과목'].replace('Math', '수학')

C:\Users\human\AppData\Local\Temp\ipykernel_13792\4170792928.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  tidy_df['과목'] = tidy_df['과목'].replace('Math', '수학')

In [ ]:
# 행의 값 수정하기
tidy_df['과목'] = tidy_df['과목'].replace('Math', '수학')
tidy_df.replace({'과목': {'Science': '과학', 'English': '영어', 'Math': '수학'}}, inplace=True) # Pandas 3.0 이후 버전에서 권장되는 방식

In [ ]:
tidy_df.sample(5)

       이름  과목    점수
8   Alice  영어  88.0
9     Bob  영어  92.0
0   Alice  수학  85.0
4   Alice  과학  90.0
10  Chris  영어   NaN

In [ ]:
tidy_df['과목'].str.replace('[학]','xx', regex=True) # regular experssion (정규식)

0     수xxx
1     수xxx
2     수xxx
3     수xxx
4     과xxx
5     과xxx
6     과xxx
7     과xxx
8       영어
9       영어
10      영어
11      영어
Name: 과목, dtype: object

In [ ]:
tidy_df['과목'].str.replace('[학]', 'x', regex=True)

0     수x
1     수x
2     수x
3     수x
4     과x
5     과x
6     과x
7     과x
8     영어
9     영어
10    영어
11    영어
Name: 과목, dtype: object

### Quiz4

[문제]
treatment.csv 파일을 불러와서 tidy data 형태로 정제하시오

In [ ]:
data = pd.read_csv("c:/Users/human/ku-python/data/treatment.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1000 non-null   object
 1   treatmenta  908 non-null    float64
 2   treatmentb  906 non-null    float64
dtypes: float64(2), object(1)
memory usage: 23.6+ KB

In [ ]:
data.head(3)

     name  treatmenta  treatmentb
0      서연        65.0        83.0
1  Olivia         2.0        91.0
2      도윤        40.0        14.0

In [ ]:
data = data.melt(id_vars=['name'], var_name='treatment', value_name='result')

In [ ]:
data = data.replace({'treatment':{'treatmenta': 'a', 'treatmentb': 'b'}})

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       2000 non-null   object
 1   treatment  2000 non-null   object
 2   result     1814 non-null   float64
dtypes: float64(1), object(2)
memory usage: 47.0+ KB

In [ ]:
# 컬럼 명 변경 후 melt
treatment = pd.read_csv('c:/Users/human/ku-python/data/treatment.csv')
treatment.rename(columns={'treatmenta': 'A', 'treatmentb': 'B'}, inplace=True)
tidy_treatment = treatment.melt(id_vars=["name"], var_name="treatment", value_name="result")

In [ ]:
# melt 후 value 값 변경
treatment = pd.read_csv('c:/Users/human/ku-python/data/treatment.csv')
tidy_treatment = treatment.melt(id_vars=["name"], var_name="treatment", value_name="result")
tidy_treatment['treatment'] = tidy_treatment['treatment'].replace({'treatmenta': 'A', 'treatmentb': 'B'})

In [ ]:
tidy_treatment

        name treatment  result
0         서연         a    65.0
1     Olivia         a     2.0
2         도윤         a    40.0
3         예진         a    13.0
4       Emma         a    25.0
...      ...       ...     ...
1995   Alice         b    44.0
1996      예진         b     5.0
1997      현우         b    86.0
1998      준호         b    41.0
1999  Sophia         b    44.0

[2000 rows x 3 columns]

### Quiz 5

[문제]
HM_all_stores.csv 파일을 불러와서 tidy data 형태로 정제하시오

[데이터 출처]
https://www.kaggle.com/datasets/shivamb/hm-stores-dataset

In [ ]:
df = pd.read_csv("c:/Users/human/ku-python/data/HM_all_stores.csv")

In [ ]:
df.sample(4)

,storeCode,storeClass,name,phone,city,country,countryCode,longitude,latitude,timeZoneIndex,...,Tue_open_hours,Wed_open_hours,Thu_open_hours,Fri_open_hours,Sat_open_hours,Sun_open_hours,streetName1,streetName2,state,address_string
3290,RU0662,Blue,ТЦ Горки,+7-8005007800,Chelyabinsk,Russian Federation,RU,61.431170,55.165191,180.0,...,10:00-22:00,10:00-22:00,10:00-22:00,10:00-22:00,10:00-22:00,10:00-22:00,ТЦ Горки,"ул. Артиллерийская, 136",Челябинская область,"ТЦ Горки;ул. Артиллерийская, 136;454007;Челяби..."
844,CO0003,Red,H&M MultiPlaza,01-800-5190076,Bogota,Colombia,CO,-74.126045,4.651365,45.0,...,10:00-21:00,10:00-21:00,10:00-21:00,10:00-21:00,10:00-21:00,10:00-20:00,H&M MultiPlaza,Calle 19 A # 72 - 57 (Avenida Boyacá con Calle...,D.C.,H&M MultiPlaza;Calle 19 A # 72 - 57 (Avenida B...
1775,GB0346,Red,H&M Milton Keynes Intu,+44-3447369000,Milton Keynes,UK,GB,-0.757799,52.041854,85.0,...,09:30-18:00,09:30-18:00,09:30-20:00,09:30-20:00,09:00-19:00,11:00-17:00,"LSU7 Unit 44, Midsummer Place",Milton Keynes,NaN,"LSU7 Unit 44, Midsummer Place;Milton Keynes;MK..."
3543,SE0471,Blue,Storhedsvägen 3,+46-33140000,Luleå,Sweden,SE,22.040548,65.618054,110.0,...,11:00-18:00,11:00-18:00,11:00-18:00,11:00-18:00,11:00-17:00,12:00-17:00,Storhedsvägen 3,NaN,NaN,Storhedsvägen 3;;97345;Luleå

In [ ]:
df.columns

Index(['storeCode', 'storeClass', 'name', 'phone', 'city', 'country',
       'countryCode', 'longitude', 'latitude', 'timeZoneIndex',
       'Mon_open_hours', 'Tue_open_hours', 'Wed_open_hours', 'Thu_open_hours',
       'Fri_open_hours', 'Sat_open_hours', 'Sun_open_hours', 'streetName1',
       'streetName2', 'state', 'address_string'],
      dtype='object')

In [ ]:
data = df.melt(id_vars=['storeCode', 'storeClass', 'name', 'phone', 'city', 'country', 'countryCode', 'longitude', 'latitude', 'timeZoneIndex', 'state', 'address_string'],
        value_vars=['Mon_open_hours', 'Tue_open_hours', 'Wed_open_hours', 'Thu_open_hours','Fri_open_hours', 'Sat_open_hours', 'Sun_open_hours'],
        var_name='day',
        value_name='opening_hours')

In [ ]:
data['day'] = data['day'].str.replace('_open_hours', '')

In [ ]:
data

,storeCode,storeClass,name,phone,city,country,countryCode,longitude,latitude,timeZoneIndex,state,address_string,day,opening_hours
0,AE0122,Red,Mirdiff city center,+971-42316646,Dubai,United Arab Emirates,AE,55.424840,25.226280,165.0,Dubai,Mirdiff city center;Sheikh Mohammad Bin Zayed ...,Mon,10:00-22:00
1,AE0149,Flagship,Dubai Mall,+971-44190346,Dubai,United Arab Emirates,AE,55.278446,25.197506,165.0,Dubai,Dubai Mall;Sheikh Zayed Road;Dubai;Dubai;Dubai,Mon,10:00-23:00
2,AE0209,Blue,Al Markaziyah,+971-26120870,Abu Dhabi,United Arab Emirates,AE,54.357462,24.487245,165.0,Abu Dhabi,Al Markaziyah;World Trade Center Mall;123;Abu ...,Mon,10:00-22:00
3,AE0223,Blue,Abu Dhabi-Dubai Rd - Abu Dhabi,+971-26120851,Abu Dhabi,United Arab Emirates,AE,54.671499,24.523875,165.0,Abu Dhabi,Abu Dhabi-Dubai Rd - Abu Dhabi;Al Bahia - Al S...,Mon,10:00-22:00
4,AE0273,Flagship,Yas Mall,+971-24926530,Abu Dhabi,United Arab Emirates,AE,54.609720,24.488684,165.0,Abu Dhabi,Yas Mall;;x;Abu Dhabi,Mon,10:00-22:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30039,ZA0028,Flagship,Canal Walk Shopping Centre,+27-860690707,Cape Town,South Africa,ZA,18.511386,-33.893271,140.0,Western Cape,"Shop 205;Century Boulevard, Century City, Cape...",Sun,09:00-21:00
30040,ZA0029,Blue,Loch Logan Waterfront,+27-860690707,Bloemfontein,South Africa,ZA,26.210716,-29.114604,140.0,Free State,Cnr henry Street and First Avenue;Westdene;930...,Sun,09:00-15:00
30041,ZA0030,Red,Cresta Shopping Centre,+27-860690707,Johannesburg,South Africa,ZA,27.983647,-26.127327,140.0,NaN,Cnr Beyers Naude Drive and Weltevreden Road;Cr...,Sun,09:00-17:00
30042,ZA0032,Blue,Eikestad Mall,+27-860690707,Cape Town,South Africa,ZA,18.859995,-33.934854,140.0,Western Cape,43 Andringa St;;7600;Stellenbosch Central;West...,Sun,09:00-14:00
30043,ZA0040,Blue,Westgate Shopping Centre,+27-860690707,Johannesburg,South Africa,ZA,27.861970,-26.137210,140.0,Gauteng,"Shop no: OOB-1, 120 Ontdekkers Road;Roodepoort...",Sun,09:00-16:00

In [ ]:
df = pd.read_csv("c:/Users/human/ku-python/data/HM_all_stores.csv", low_memory=False)

# 운영 시간 관련 컬럼 추출 (요일별 오픈 시간 데이터)
opening_hours_cols = [col for col in df.columns if '_open_hours' in col]

# 운영 시간 관련 컬럼을 long format으로 변환
df_tidy = df.melt(id_vars=['storeCode', 'storeClass', 'name', 'city', 'country', 'countryCode', 'longitude', 'latitude'],
                  value_vars=opening_hours_cols,
                  var_name='day_of_week',
                  value_name='opening_hours')

# '_open_hours' 접미사를 제거하여 요일 정보만 남기기
df_tidy['day_of_week'] = df_tidy['day_of_week'].str.replace('_open_hours', '')

In [ ]:
df_tidy

,storeCode,storeClass,name,city,country,countryCode,longitude,latitude,day_of_week,opening_hours
0,AE0122,Red,Mirdiff city center,Dubai,United Arab Emirates,AE,55.424840,25.226280,Mon,10:00-22:00
1,AE0149,Flagship,Dubai Mall,Dubai,United Arab Emirates,AE,55.278446,25.197506,Mon,10:00-23:00
2,AE0209,Blue,Al Markaziyah,Abu Dhabi,United Arab Emirates,AE,54.357462,24.487245,Mon,10:00-22:00
3,AE0223,Blue,Abu Dhabi-Dubai Rd - Abu Dhabi,Abu Dhabi,United Arab Emirates,AE,54.671499,24.523875,Mon,10:00-22:00
4,AE0273,Flagship,Yas Mall,Abu Dhabi,United Arab Emirates,AE,54.609720,24.488684,Mon,10:00-22:00
...,...,...,...,...,...,...,...,...,...,...
30039,ZA0028,Flagship,Canal Walk Shopping Centre,Cape Town,South Africa,ZA,18.511386,-33.893271,Sun,09:00-21:00
30040,ZA0029,Blue,Loch Logan Waterfront,Bloemfontein,South Africa,ZA,26.210716,-29.114604,Sun,09:00-15:00
30041,ZA0030,Red,Cresta Shopping Centre,Johannesburg,South Africa,ZA,27.983647,-26.127327,Sun,09:00-17:00
30042,ZA0032,Blue,Eikestad Mall,Cape Town,South Africa,ZA,18.859995,-33.934854,Sun,09:00-14:00
30043,ZA0040,Blue,Westgate Shopping Centre,Johannesburg,South Africa,ZA,27.861970,-26.137210,Sun,09:00-16:00

In [ ]:
import numpy as np

In [ ]:
np.nan

nan

In [ ]:
test = np.array([1,2,3,4])

In [ ]:
type(test)

numpy.ndarray

### 결측치 처리

1. nan 값 확인하기 
2. nan 값 삭제하기 
3. nan 값 대체하기
4. nan 값 보완하기

In [ ]:
data = pd.read_csv('c:/Users/human/ku-python/data/treatment.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1000 non-null   object
 1   treatmenta  908 non-null    float64
 2   treatmentb  906 non-null    float64
dtypes: float64(2), object(1)
memory usage: 23.6+ KB

In [ ]:
data.isnull().sum()

name           0
treatmenta    92
treatmentb    94
dtype: int64

In [ ]:
data.isna().sum()

name           0
treatmenta    92
treatmentb    94
dtype: int64

In [ ]:
len(data)

1000

In [ ]:
data.dropna(inplace=True)

In [ ]:
data

       name  treatmenta  treatmentb
0        서연        65.0        83.0
1    Olivia         2.0        91.0
2        도윤        40.0        14.0
4      Emma        25.0         1.0
6     David        74.0        72.0
..      ...         ...         ...
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0
999  Sophia        13.0        44.0

[824 rows x 3 columns]

In [ ]:
data.dropna(axis=0) # axis = 0 행 단위로 연산 / axis = 1 열 단위로 연산

       name  treatmenta  treatmentb
0        서연        65.0        83.0
1    Olivia         2.0        91.0
2        도윤        40.0        14.0
4      Emma        25.0         1.0
6     David        74.0        72.0
..      ...         ...         ...
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0
999  Sophia        13.0        44.0

[824 rows x 3 columns]

In [ ]:
data.dropna(axis=0, how='all') # 모든 값이 NaN인 행 삭제 / how='any'는 하나라도 NaN이면 삭제

       name  treatmenta  treatmentb
0        서연        65.0        83.0
1    Olivia         2.0        91.0
2        도윤        40.0        14.0
3        예진        13.0         NaN
4      Emma        25.0         1.0
..      ...         ...         ...
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0
999  Sophia        13.0        44.0

[1000 rows x 3 columns]

In [ ]:
data

       name  treatmenta  treatmentb
0        서연        65.0        83.0
1    Olivia         2.0        91.0
2        도윤        40.0        14.0
3        예진        13.0         NaN
4      Emma        25.0         1.0
..      ...         ...         ...
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0
999  Sophia        13.0        44.0

[1000 rows x 3 columns]

In [ ]:
data.fillna(0) # NaN 값을 0으로 채움

       name  treatmenta  treatmentb
0        서연        65.0        83.0
1    Olivia         2.0        91.0
2        도윤        40.0        14.0
3        예진        13.0        50.0
4      Emma        25.0         1.0
..      ...         ...         ...
995   Alice        59.0        44.0
996      예진        99.0         5.0
997      현우        57.0        86.0
998      준호        76.0        41.0
999  Sophia        13.0        44.0

[1000 rows x 3 columns]

In [ ]:
data['treatmentb']

0      83.0
1      91.0
2      14.0
3       NaN
4       1.0
       ...
995    44.0
996     5.0
997    86.0
998    41.0
999    44.0
Name: treatmentb, Length: 1000, dtype: float64

In [ ]:
data['treatmentb'].interpolate() # NaN 값의 앞 뒤 데이터를 이용하여 선형 보간을 함. 🛠️ 선형 보간: 두 값의 직선 경로에서 직선 관계를 유지하도록 보정된 값.

0      83.0
1      91.0
2      14.0
3       7.5
4       1.0
       ...
995    44.0
996     5.0
997    86.0
998    41.0
999    44.0
Name: treatmentb, Length: 1000, dtype: float64

### Quiz 6
> HM_all_stores.csv 파일을 불러오고 결측치가 포함되어 있는 행을 모두 제거하시오.

In [ ]:
df = pd.read_csv("c:/Users/human/ku-python/data/HM_all_stores.csv")

In [ ]:
df.isna().sum()

storeCode            0
storeClass           3
name                 2
phone              152
city                 0
country              0
countryCode          0
longitude            0
latitude             0
timeZoneIndex        3
Mon_open_hours      34
Tue_open_hours      34
Wed_open_hours      34
Thu_open_hours      34
Fri_open_hours      34
Sat_open_hours      34
Sun_open_hours    1144
streetName1          0
streetName2       2465
state             1861
address_string       0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isna().sum()

storeCode         0
storeClass        0
name              0
phone             0
city              0
country           0
countryCode       0
longitude         0
latitude          0
timeZoneIndex     0
Mon_open_hours    0
Tue_open_hours    0
Wed_open_hours    0
Thu_open_hours    0
Fri_open_hours    0
Sat_open_hours    0
Sun_open_hours    0
streetName1       0
streetName2       0
state             0
address_string    0
dtype: int64

### Quiz 7
> HM_all_stores.csv 파일을 불러오고 결측치가 있을 경우 선형보간법으로 값을 대체하시오 <br>
> nearest 방식으로도 대체 하시오. <br>
> 문자열 방식은 대체방식으로 결측치를 제거 하세요

In [ ]:
df = pd.read_csv("c:/Users/human/ku-python/data/HM_all_stores.csv")

In [ ]:
df.interpolate(inplace=True)

C:\Users\human\AppData\Local\Temp\ipykernel_13792\471562723.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(inplace=True)

In [ ]:
df.fillna('', inplace=True)

C:\Users\human\AppData\Local\Temp\ipykernel_13792\1272664119.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna('', inplace=True)

In [ ]:
df[['timeZoneIndex']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4292 entries, 0 to 4291
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timeZoneIndex  4292 non-null   object
dtypes: object(1)
memory usage: 33.7+ KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4292 entries, 0 to 4291
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   storeCode       4292 non-null   object
 1   storeClass      4292 non-null   object
 2   name            4292 non-null   object
 3   phone           4292 non-null   object
 4   city            4292 non-null   object
 5   country         4292 non-null   object
 6   countryCode     4292 non-null   object
 7   longitude       4292 non-null   float64
 8   latitude        4292 non-null   float64
 9   timeZoneIndex   4292 non-null   object
 10  Mon_open_hours  4292 non-null   object
 11  Tue_open_hours  4292 non-null   object
 12  Wed_open_hours  4292 non-null   object
 13  Thu_open_hours  4292 non-null   object
 14  Fri_open_hours  4292 non-null   object
 15  Sat_open_hours  4292 non-null   object
 16  Sun_open_hours  4292 non-null   object
 17  streetName1     4292 non-null   object
 18  streetName2     4292 non-null   object
 19  state           4292 non-null   object
 20  address_string  4292 non-null   object
dtypes: float64(2), object(19)
memory usage: 704.3+ KB

## 집계 분석(Aggregation analysis)

1. groupby 
- 특정 컬럼을 기준으로 그룹화하여 통계 연산을 수행하는 함수 
2. pivot table 
- 엑셀의 피벗 테이블과 유사한 기능으로, 데이터를 그룹화 하고 요약하는 함수 
3. crosstab 
- 두 개 이상의 범주형 변수 간의 빈도수를 계산하는데 사용하는 함수

### Groupby 

1. 그룹화할 기준 컬럼 선정 
2. 통계 연산 선정
3. 그룹별 조건 적용

In [ ]:
data = pd.read_csv('c:/Users/human/ku-python/data/treatment.csv')

In [ ]:
data.groupby('name').mean()

          treatmenta  treatmentb
name
Alice      46.704545   53.575000
David      52.812500   47.750000
Emma       48.071429   56.024390
Isabella   51.660000   48.000000
James      47.131579   47.324324
John       47.740741   55.392157
Michael    48.833333   55.823529
Olivia     48.425000   48.022222
Robert     51.594595   42.078947
Sophia     48.163636   50.166667
도윤         46.200000   55.672727
민수         41.416667   48.531250
서연         46.041667   47.080000
수빈         55.229167   46.232558
영희         46.588235   52.527778
예진         48.782609   48.212766
준호         42.450980   55.653846
지연         56.146341   53.177778
철수         47.767857   51.714286
현우         47.867925   55.122449

In [ ]:
data.groupby('name').sum()

          treatmenta  treatmentb
name
Alice         2055.0      2143.0
David         1690.0      1528.0
Emma          2019.0      2297.0
Isabella      2583.0      2496.0
James         1791.0      1751.0
John          2578.0      2825.0
Michael       2344.0      2847.0
Olivia        1937.0      2161.0
Robert        1909.0      1599.0
Sophia        2649.0      2709.0
도윤            2541.0      3062.0
민수            1491.0      1553.0
서연            2210.0      2354.0
수빈            2651.0      1988.0
영희            1584.0      1891.0
예진            2244.0      2266.0
준호            2165.0      2894.0
지연            2302.0      2393.0
철수            2675.0      2896.0
현우            2537.0      2701.0

In [ ]:
data.groupby('name')['treatmenta'].mean()

name
Alice       46.704545
David       52.812500
Emma        48.071429
Isabella    51.660000
James       47.131579
John        47.740741
Michael     48.833333
Olivia      48.425000
Robert      51.594595
Sophia      48.163636
도윤          46.200000
민수          41.416667
서연          46.041667
수빈          55.229167
영희          46.588235
예진          48.782609
준호          42.450980
지연          56.146341
철수          47.767857
현우          47.867925
Name: treatmenta, dtype: float64

In [ ]:
data.groupby('name')['treatmenta'].agg(['sum', 'mean', 'count', 'max', 'min'])

             sum       mean  count    max  min
name
Alice     2055.0  46.704545     44  100.0  0.0
David     1690.0  52.812500     32   99.0  0.0
Emma      2019.0  48.071429     42  100.0  3.0
Isabella  2583.0  51.660000     50   99.0  4.0
James     1791.0  47.131579     38   98.0  4.0
John      2578.0  47.740741     54  100.0  4.0
Michael   2344.0  48.833333     48  100.0  1.0
Olivia    1937.0  48.425000     40   99.0  1.0
Robert    1909.0  51.594595     37   97.0  2.0
Sophia    2649.0  48.163636     55  100.0  0.0
도윤        2541.0  46.200000     55   94.0  0.0
민수        1491.0  41.416667     36   97.0  1.0
서연        2210.0  46.041667     48   97.0  0.0
수빈        2651.0  55.229167     48  100.0  1.0
영희        1584.0  46.588235     34  100.0  1.0
예진        2244.0  48.782609     46   99.0  1.0
준호        2165.0  42.450980     51   98.0  2.0
지연        2302.0  56.146341     41   98.0  2.0
철수        2675.0  47.767857     56  100.0  4.0
현우        2537.0  47.867925     53   99.0  2.0

In [ ]:
data.groupby('name')['treatmenta'].apply(lambda x: x.max() - x.min()) # 최대값과 최소값의 차이

name
Alice       100.0
David        99.0
Emma         97.0
Isabella     95.0
James        94.0
John         96.0
Michael      99.0
Olivia       98.0
Robert       95.0
Sophia      100.0
도윤           94.0
민수           96.0
서연           97.0
수빈           99.0
영희           99.0
예진           98.0
준호           96.0
지연           96.0
철수           96.0
현우           97.0
Name: treatmenta, dtype: float64

### Pivot_table 
> groupby 연산과 유사하지만 <br>
> 좀 더 복잡한 다차원 데이터를 그룹화 하는데 가독성이 더 좋음 <br>
> 결측치 처리가 옵션으로 사용 할 수 있어서 좀 더 편리


1. index → 그룹화할 기준 컬럼 선정 
2. columns → 새로운 열로 변환할 컬럼 
3. values → 집계할 값 (수치형 데이터)
4. aggfunc → 집계 함수

In [ ]:
data = pd.read_csv('c:/Users/human/ku-python/data/treatment.csv')

In [ ]:
data.head()

     name  treatmenta  treatmentb
0      서연        65.0        83.0
1  Olivia         2.0        91.0
2      도윤        40.0        14.0
3      예진        13.0         NaN
4    Emma        25.0         1.0

In [ ]:
data.pivot_table(index='name', values=['treatmenta', 'treatmentb'], aggfunc='mean') #  data.groupby('name').mean()와 같은 연산

          treatmenta  treatmentb
name
Alice      46.704545   53.575000
David      52.812500   47.750000
Emma       48.071429   56.024390
Isabella   51.660000   48.000000
James      47.131579   47.324324
John       47.740741   55.392157
Michael    48.833333   55.823529
Olivia     48.425000   48.022222
Robert     51.594595   42.078947
Sophia     48.163636   50.166667
도윤         46.200000   55.672727
민수         41.416667   48.531250
서연         46.041667   47.080000
수빈         55.229167   46.232558
영희         46.588235   52.527778
예진         48.782609   48.212766
준호         42.450980   55.653846
지연         56.146341   53.177778
철수         47.767857   51.714286
현우         47.867925   55.122449

In [ ]:
data.pivot_table(index=['name'], values=['treatmenta','treatmentb'], aggfunc='mean', fill_value=50)

          treatmenta  treatmentb
name
Alice      46.704545   53.575000
David      52.812500   47.750000
Emma       48.071429   56.024390
Isabella   51.660000   48.000000
James      47.131579   47.324324
John       47.740741   55.392157
Michael    48.833333   55.823529
Olivia     48.425000   48.022222
Robert     51.594595   42.078947
Sophia     48.163636   50.166667
도윤         46.200000   55.672727
민수         41.416667   48.531250
서연         46.041667   47.080000
수빈         55.229167   46.232558
영희         46.588235   52.527778
예진         48.782609   48.212766
준호         42.450980   55.653846
지연         56.146341   53.177778
철수         47.767857   51.714286
현우         47.867925   55.122449

In [ ]:
import pandas as pd

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C', 'C', 'B'],
    'Year': [2022, 2022, 2023, 2023, 2023, 2022, 2023, 2022],
    'Sales': [100, 150, 200, 130, 170, 90, 120, 160]
}

df = pd.DataFrame(data)
pivot = df.pivot_table(index='Category', columns='Year', values='Sales', aggfunc='sum')

In [ ]:
pivot

Year      2022  2023
Category
A          100   370
B          310   130
C           90   120

In [ ]:
df.groupby(['Category','Year']).sum()

               Sales
Category Year
A        2022    100
         2023    370
B        2022    310
         2023    130
C        2022     90
         2023    120

In [ ]:
data = {
    'Product': ['A', 'A', 'A', 'A', 'B', 'B', 'C', 'C', 'C', 'C'],
    'Region': ['North', 'North', 'East', 'East', 'South', 'South', 'East', 'East', 'East', 'North'],
    'Sales': [100, 150, 200, 250, 300, 250, 300, 300, 400, 100]
}

df = pd.DataFrame(data)

In [ ]:
df

  Product Region  Sales
0       A  North    100
1       A  North    150
2       A   East    200
3       A   East    250
4       B  South    300
5       B  South    250
6       C   East    300
7       C   East    300
8       C   East    400
9       C  North    100

In [ ]:
pivot_result = pd.pivot_table(df, values='Sales', index='Product', columns='Region', aggfunc='sum', fill_value=0)

In [ ]:
pivot_result

Region   East  North  South
Product
A         450    250      0
B           0      0    550
C        1000    100      0

In [ ]:
df.groupby(['Product', 'Region']).sum()

                Sales
Product Region
A       East      450
        North     250
B       South     550
C       East     1000
        North     100

### Crosstab
> 빈도 분석에 특화된 함수

1. index → 행 기준 (Y축)
2. columns → 열 기준 (X축)
3. values → 집계할 수치형 데이터 (기본값은 빈도수)
4. aggfunc → values에 대한 집계 함수 (예: sum, mean 등)
5. margins=True → 총합(Total) 추가
6. normalize=True → 비율(%) 출력

In [ ]:
import pandas as pd

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C', 'C', 'B'],
    'Year': [2022, 2022, 2023, 2023, 2023, 2022, 2023, 2022],
    'Sales': [100, 150, 200, 130, 170, 90, 120, 160]
}

df = pd.DataFrame(data)

In [ ]:
pd.crosstab(index=df['Category'], 
            columns=df['Year'], 
            values=df['Sales'], 
            aggfunc='sum', margins=True)

Year      2022  2023   All
Category
A          100   370   470
B          310   130   440
C           90   120   210
All        500   620  1120

In [ ]:
pd.crosstab(index=df['Category'], 
            columns=df['Year'], 
            values=df['Sales'], aggfunc='sum', normalize=True)

Year          2022      2023
Category
A         0.089286  0.330357
B         0.276786  0.116071
C         0.080357  0.107143

In [ ]:
pd.crosstab(index=df['Category'], 
            columns=df['Year'], 
            values=df['Sales'],
            aggfunc='sum', margins=True, normalize=True)

Year          2022      2023       All
Category
A         0.089286  0.330357  0.419643
B         0.276786  0.116071  0.392857
C         0.080357  0.107143  0.187500
All       0.446429  0.553571  1.000000

In [ ]:
df

  Category  Year  Sales
0        A  2022    100
1        B  2022    150
2        A  2023    200
3        B  2023    130
4        A  2023    170
5        C  2022     90
6        C  2023    120
7        B  2022    160

In [ ]:
pd.crosstab(df['Category'], df['Year']) # 기본값은 count

Year      2022  2023
Category
A            1     2
B            2     1
C            1     1

In [ ]:
pd.crosstab(df['Year'], df['Category'])

Category  A  B  C
Year
2022      1  2  1
2023      2  1  1

### Quiz 8
> pathogenicity_scores.csv 파일을 불러오고 Mutation_ID가 12000에서 12010 사이인 데이터에서, <br>
> Patient_ID를 기준으로 그룹화하고, SCORE_A의 평균 값을 구하라.

In [ ]:
data = pd.read_csv('c:/Users/human/ku-python/data/pathogenicity_scores.csv')

In [ ]:
filtered_data = data[(data['Mutation_ID'] >= 12000) & (data['Mutation_ID'] <= 12010)]

In [ ]:
filtered_data.pivot_table(index='Patient_ID', values='SCORE_A', aggfunc='mean')

            SCORE_A
Patient_ID
55            0.494
56            0.199
110           0.030

In [ ]:
# data = pd.read_csv('c:/Users/human/ku-python/data/pathogenicity_scores.csv')
# test = data[(data['Mutation_ID'] >= 12000) & (data['Mutation_ID'] <= 12010)] # data[data['Mutation_ID'].between(12000, 12010)]
# test.pivot_table(index='Patient_ID', columns='Mutation_ID', values='SCORE_A', aggfunc='mean')

## 데이터 프레임 파일로 저장하기

In [ ]:
data = {
    'ID': ['아이디1', '아이디2', '아이디3', 'id1', 'id2', 'id3', 'id4'],
    'Product': ['A', 'A', 'B', 'B', 'C', 'C', 'C'],
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'East'],
    'Sales': [100, 150, 200, 250, 300, 300, 400]
}
df = pd.DataFrame(data)

In [ ]:
df

     ID Product Region  Sales
0  아이디1       A  North    100
1  아이디2       A  North    150
2  아이디3       B  South    200
3   id1       B  South    250
4   id2       C   East    300
5   id3       C   East    300
6   id4       C   East    400

to_csv

In [ ]:
df.to_csv('data/test.csv', index=False, encoding='utf-8-sig')

In [ ]:
df.to_csv('data/test.csv') # index를 포함하여 저장

to_excel

In [ ]:
# pip install openpyxl (excel 파일을 다루기 위해서 필요한 라이브러리)
df.to_excel('data/test.xlsx', index=False)

### Quiz 9

1. 각 컬럼의 데이터 타입을 적절한 형태로 변환 하세요.
2. country를 기준으로 그룹화 하고, 매장 개수가 몇개 있는지 확인하기 (storeCode)

In [ ]:
df = pd.read_csv("c:/Users/human/ku-python/data/HM_all_stores.csv")

In [ ]:
df.head()

,storeCode,storeClass,name,phone,city,country,countryCode,longitude,latitude,timeZoneIndex,...,Tue_open_hours,Wed_open_hours,Thu_open_hours,Fri_open_hours,Sat_open_hours,Sun_open_hours,streetName1,streetName2,state,address_string
0,AE0122,Red,Mirdiff city center,+971-42316646,Dubai,United Arab Emirates,AE,55.424840,25.226280,165.0,...,10:00-22:00,10:00-22:00,10:00-23:55,10:00-23:55,10:00-23:55,10:00-22:00,Mirdiff city center,Sheikh Mohammad Bin Zayed Road,Dubai,Mirdiff city center;Sheikh Mohammad Bin Zayed ...
1,AE0149,Flagship,Dubai Mall,+971-44190346,Dubai,United Arab Emirates,AE,55.278446,25.197506,165.0,...,10:00-23:00,10:00-23:00,10:00-23:55,10:00-23:55,10:00-23:00,10:00-23:00,Dubai Mall,Sheikh Zayed Road,Dubai,Dubai Mall;Sheikh Zayed Road;Dubai;Dubai;Dubai
2,AE0209,Blue,Al Markaziyah,+971-26120870,Abu Dhabi,United Arab Emirates,AE,54.357462,24.487245,165.0,...,10:00-22:00,10:00-22:00,10:00-23:00,10:00-23:00,10:00-22:00,10:00-22:00,Al Markaziyah,World Trade Center Mall,Abu Dhabi,Al Markaziyah;World Trade Center Mall;123;Abu ...
3,AE0223,Blue,Abu Dhabi-Dubai Rd - Abu Dhabi,+971-26120851,Abu Dhabi,United Arab Emirates,AE,54.671499,24.523875,165.0,...,10:00-22:00,10:00-22:00,10:00-23:55,10:00-23:55,10:00-20:00,10:00-22:00,Abu Dhabi-Dubai Rd - Abu Dhabi,Al Bahia - Al Shahama,Abu Dhabi,Abu Dhabi-Dubai Rd - Abu Dhabi;Al Bahia - Al S...
4,AE0273,Flagship,Yas Mall,+971-24926530,Abu Dhabi,United Arab Emirates,AE,54.609720,24.488684,165.0,...,10:00-22:00,10:00-22:00,10:00-23:55,10:00-23:55,10:00-22:00,10:00-22:00,Yas Mall,NaN,Abu Dhabi,Yas Mall;;x;Abu Dhabi

In [ ]:
df = pd.read_csv("data/HM_all_stores.csv", low_memory=False)

# 운영 시간 관련 컬럼 추출 (요일별 오픈 시간 데이터)
opening_hours_cols = [col for col in df.columns if '_open_hours' in col]

# 운영 시간 관련 컬럼을 long format으로 변환
df_tidy = df.melt(id_vars=['storeCode', 'storeClass', 'name', 'city', 'country', 'countryCode', 'longitude', 'latitude'],
                  value_vars=opening_hours_cols,
                  var_name='day_of_week',
                  value_name='opening_hours')

# '_open_hours' 접미사를 제거하여 요일 정보만 남기기
df_tidy['day_of_week'] = df_tidy['day_of_week'].str.replace('_open_hours', '')

In [ ]:
df_tidy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30044 entries, 0 to 30043
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   storeCode      30044 non-null  object
 1   storeClass     30023 non-null  object
 2   name           30030 non-null  object
 3   city           30044 non-null  object
 4   country        30044 non-null  object
 5   countryCode    30044 non-null  object
 6   longitude      30044 non-null  float64
 7   latitude       30044 non-null  float64
 8   day_of_week    30044 non-null  category
 9   opening_hours  28696 non-null  category
dtypes: category(2), float64(2), object(6)
memory usage: 1.9+ MB

In [ ]:
df_tidy['day_of_week']=df_tidy['day_of_week'].astype('category')
df_tidy['opening_hours']=df_tidy['opening_hours'].astype('category')
df_tidy['longitude']=df_tidy['longitude'].astype('float32')
df_tidy['latitude']=df_tidy['latitude'].astype('float32')

In [ ]:
df_tidy.pivot_table(index='country', values='storeCode', aggfunc='count')

                      storeCode
country
Australia                   252
Austria                     539
Bahrain                      28
Belarus                      21
Belgium                     455
...                         ...
USA                        3724
Ukraine                      63
United Arab Emirates        231
Uruguay                      21
Viet Nam                     84

[74 rows x 1 columns]

### Quiz 10

1. 데이터 셋에서 결측치를 원하는 방식대로 처리하세요.
2. 각 컬럼의 데이터 타입을 적절한 형태로 변환 하세요.
3. 평점이 4.5 이상인 제품 중 리뷰 수가 가장 많은 상위 5개 제품을 찾으시오.
4. 각 카테고리 별 제품 개수를 집계 내고 엑셀파일로 저장하시오.

[출처]
https://www.kaggle.com/datasets/karkavelrajaj/amazon-sales-dataset

Structured array
    > 구조화된 배열
    > 서로다른 데이터 타입으로 구성된 배열
    > 서로다른 ndarray 데이터로 구성된 배열

In [ ]:
import numpy as np

In [102]:
test = np.array([1, 2, 3])

In [103]:
test

array([1, 2, 3])

In [ ]:
x = np.array([('jihyuk', 25, 73.0),
              ('thor', 35, 85.0),
              ('lion', 10, 30.0)],
              dtype=[('name', 'U10', 'age', 'i4', 'weight', 'f4')])

TypeError: Field elements must be tuples with at most 3 elements, got '('name', 'U10', 'age', 'i4', ('weight', 'f4'))'

In [105]:
type(x)

NameError: name 'x' is not defined